#define ASS_DEPT_NONE "None"
#define ASS_DEPT_ENGINEERING "Engineering"
#define ASS_DEPT_MEDICAL "Medical"
#define ASS_DEPT_SCIENCE "Science"
#define ASS_DEPT_SECURITY "Security"
#define ASS_DEPT_SERVICE "Service"
#define ASS_DEPT_SUPPLY "Supply"
